import * as React from "react";
import {
  Body,
  Container,
  Head,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";

type BaseLayoutProps = {
  previewText: string;
  heading: string;
  children: React.ReactNode;
};

export function BaseLayout({ previewText, heading, children }: BaseLayoutProps) {
  return (
    <Html>
      <Head />
      <Preview>{previewText}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Section style={styles.header}>
            <Text style={styles.title}>Flight Schedule Pro</Text>
            <Text style={styles.heading}>{heading}</Text>
          </Section>
          <Section>{children}</Section>
          <Section style={styles.footer}>
            <Text style={styles.footerText}>
              This message was generated by the Flight Lesson Rescheduler demo.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

const styles = {
  body: {
    backgroundColor: "#f6f6f6",
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    padding: "24px 0",
  },
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.08)",
    padding: "32px",
    maxWidth: "640px",
  },
  header: {
    marginBottom: "16px",
  },
  title: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#2563eb",
    marginBottom: "4px",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  heading: {
    fontSize: "22px",
    fontWeight: 600,
    color: "#0f172a",
    margin: 0,
  },
  footer: {
    borderTop: "1px solid #e2e8f0",
    marginTop: "24px",
    paddingTop: "16px",
  },
  footerText: {
    fontSize: "12px",
    color: "#64748b",
  },
} satisfies Record<string, React.CSSProperties>;
